Practice/Myown/Myapp/urls.py
from django.conf.urls import url
from Myapp import views

app_name='Myapp'

urlpatterns=[
    url('relative/', views.relative, name='relative'),
    url('other/', views.other, name='other'),
    url('register/', views.register, name='register'),
    url('user_login/', views.user_login, name='user_login'),
]

Practice/Myown/Myown/Myown/urls.py
from django.contrib import admin
from django.urls import path
from Myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('user/', views.users, name='user'),
    path('formpage/', views.form_name_view, name='form_name')
]

Practice/Myown/Myown/urls.py
from django.contrib import admin
from django.urls import path, include
from Myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('user/', views.users, name='user'),
    path('formpage/', views.form_name_view, name='form_name'),
    path('Myapp/', include('Myapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

Practice/Myown/Myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class user(models.Model):
    first_name=models.CharField(max_length=128)
    last_name=models.CharField(max_length=128)
    e_mail=models.EmailField(max_length=264, unique=True)

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Practice/Myown/Myown/Myapp/models.py
from django.db import models

# Create your models here.
class user(models.Model):
    first_name=models.CharField(max_length=128)
    last_name=models.CharField(max_length=128)
    e_mail=models.EmailField(max_length=264, unique=True)

Practice/Myown/basic_app/models.py
from django.db import models

# Create your models here.

Practice/Myown/Myapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from Myapp.models import user, UserProfileInfo

class FormName(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    verify_email=forms.EmailField(label='Enter your email again:')
    text=forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data=super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MATCH!")
class NewUserForm(forms.ModelForm):
    class Meta():
        model=user
        fields='__all__'

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site', 'profile_pic')

Practice/Myown/Myown/Myapp/forms.py
from django import forms
from django.core import validators
from Myapp.models import user

class FormName(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    verify_email=forms.EmailField(label='Enter your email again:')
    text=forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data=super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MATCH!")
class NewUserForm(forms.ModelForm):
    class Meta():
        model=user
        fields='__all__'

Practice/Myown/Myapp/views.py
from django.shortcuts import render
from . import forms
from Myapp.forms import NewUserForm, UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, 'Myapp/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered=True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request, 'Myapp/registration.html', {'user_form':user_form,'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username:{} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'Myapp/login.html')

def users(request):
    form=NewUserForm()
    if request.method=="POST":
        form=NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
    return render(request, 'user.html', {'form':form})

def form_name_view(request):
    form=forms.FormName()

    if request.method == 'POST':
        form=forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])

    return render(request, 'form_page.html', {'form':form})

def other(request):
    return render(request, 'other.html')

def relative(request):
    return render(request, 'relative_url_templates.html')

Practice/Myown/Myown/Myapp/views.py
from django.shortcuts import render
from . import forms
from Myapp.forms import NewUserForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def users(request):
    form=NewUserForm()
    if request.method=="POST":
        form=NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
    return render(request, 'user.html', {'form':form})

def form_name_view(request):
    form=forms.FormName()

    if request.method == 'POST':
        form=forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])

    return render(request, 'form_page.html', {'form':form})

Practice/Myown/basic_app/views.py
from django.shortcuts import render

# Create your views here.

Practice/Myown/Myapp/templates/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

Practice/Myown/Myapp/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <h2>Go to /users to sign up!</h2>
      </div>
    </div>
  </body>
</html>

Practice/Myown/Myapp/templates/user.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h1>Please sign up here!</h1>
        <form method="POST">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class='btn btn-primary' value="submit">
        </form>
    </div>
  </body>
</html>

Practice/Myown/Myown/Myapp/templates/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

Practice/Myown/Myown/Myapp/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <h2>Go to /users to sign up!</h2>
      </div>
    </div>
  </body>
</html>

Practice/Myown/Myown/Myapp/templates/user.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h1>Please sign up here!</h1>
        <form method="POST">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class='btn btn-primary' value="submit">
        </form>
    </div>
  </body>
</html>

Practice/Myown/templates/Myapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="navbar-link"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="navbar-link"><a class="nav-link" href="{% url 'Myapp:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li class="navbar-link"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class="navbar-link"><a class="nav-link" href="{% url 'Myapp:user_login' %}">Login</a></li>
          {% endif%}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Practice/Myown/templates/Myapp/index.html
{% extends "Myapp/base.html"%}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

Practice/Myown/templates/Myapp/login.html
{% extends 'Myapp/base.html'%}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'Myapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>

</div>
{% endblock %}

Practice/Myown/templates/Myapp/registration.html
{% extends "Myapp/base.html"%}
{% load static %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class='btn btn-primary' value="register">
    </form>
  {% endif %}

</div>
{% endblock %}

Practice/Myown/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Basic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'Myapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

Practice/Myown/templates/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

Practice/Myown/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
    {% block body_block%}
    <h1>WELCOME TO INDEX!</h1>
    <!-- <h1>This is index.html page showing!</h1> -->
    <h1>{{ text | cut:'world'}}</h1>
    <h1>{{ number | add:"99"}}</h1>
    {% endblock %}

Practice/Myown/templates/other.html
<!DOCTYPE html>
{% extends 'base.html' %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

Practice/Myown/templates/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href='{% url 'Myapp:other' %}'>THE OTHER PAGE</a>
    <a href='{% url 'admin:index' %}'>THE OTHER PAGE</a>
  </body>
</html>

Practice/Myown/templates/user.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h1>Please sign up here!</h1>
        <form method="POST">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class='btn btn-primary' value="submit">
        </form>
    </div>
  </body>
</html>